return {

  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      vim.list_extend(opts.ensure_installed, {
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "gpg",
        "groovy",
        "hcl",
        "html",
        "ini",
        "java",
        "javascript",
        "jq",
        "json",
        "latex",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "ninja",
        "nix",
        -- "norg",
        "passwd",
        "pem",
        "perl",
        "php",
        "promql",
        "proto",
        "regex",
        "ron",
        "rst",
        "ruby",
        "rust",
        "scss",
        "sql",
        "strace",
        "terraform",
        "toml",
        "tsv",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
        "yuck",
      })
    end,
  },

  {
    "windwp/nvim-ts-autotag",
    ft = {
      "html",
      "javascript",
      "javascriptreact",
      "jsx",
      "tsx",
      "typescript",
      "typescriptreact",
      "markdown",
    },
    config = true,
  },

}
